name: Deploy NodeJS server to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: convohub
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ../../var/www/swifttalk/SwiftTalk-Chat-Messaging-App/
            git config --global --add safe.directory /var/www/swifttalk/SwiftTalk-Chat-Messaging-App
            git stash
            git pull
            cd server
            npx prisma generate
            npx prisma migrate deploy
            npm install
            pm2 restart swifttalk-server